### ISSUE TITLE
Paint expansion

### ISSUE THREAD

**Issue by dnguyen-thi** [saalfeldlab/paintera#376]
Hi,

I wanted to mention an issue that I have been experiencing while working with Paintera.
We are currently using Paintera to achieve dense segmentation in our dataset.

First, the smallest brush size is still bigger than a voxel. In fact, it usually paints in a (+) shape which makes reaching certain corners difficult.
Additionally, the paint tends to expand after Paintera computes the changes I make. For instance, if I intended to paint 5 voxels, 7-8 voxels end up with that segment ID. 

Do you have a proposed solution for this issue I am experiencing? 

Thanks!

**Comment by hanslovsky** [comment]
Thank you for reporting this issue @dnguyen-thi 

I will start with (part of) your first issue, the smallest brush size being bigger than a voxel: This was reported in #354 and fixed in #355. We are trying to release Paintera this week or next week so, hopefully, this will be fixed automatically, soon.

Regarding the expanding paint, I do not have an answer at this moment and we will have to investigate, what exactly is going wrong there. I tried for myself and I can confirm this erroneous behavior of Paintera. It seems that the resolution of the mask (technical detail) may be inconsistent with the resolution of the data.

cc @igorpisarev

**Comment by dnguyen-thi** [comment]
Hi again!

I've recently updated Paintera to 0.22.0 and would like to mention that although the newer version does fulfill my initial request for a smaller brush size, paint expansion still occurs. For that reason, I am still experiencing the same painting restrictions as per prior to the update. 

Thank you!

**Comment by hanslovsky** [comment]
Thank you for reporting back. The Paint expansion issue has not been addressed yet.

**Comment by hanslovsky** [comment]
@igorpisarev I am currently looking into this and right now I have no clue where it is going wrong. I am looking at the `MaskedSource` to see if maybe the transforms are incorrect.

One thing that I noticed is that the transforms for the interpolated and scaled masks may be set incorrectly in [`MaskedSource.setMaskScaleLevels`](https://github.com/saalfeldlab/paintera/blob/074c2279da9c80844961b3e555e7dbfea9706404/src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSource.java#L1544).
 1. As far as I can tell, the [transform can be simplified to](https://github.com/saalfeldlab/paintera/blob/074c2279da9c80844961b3e555e7dbfea9706404/src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSource.java#L1564-L1567) `levelToFullResTransform[level].inverse()`
 2. The concatenation order may be incorrect, i.e. [`levelToFullResTransform[level].preConcatenate(fullResTransform.inverse())`](https://github.com/saalfeldlab/paintera/blob/074c2279da9c80844961b3e555e7dbfea9706404/src/main/java/org/janelia/saalfeldlab/paintera/data/mask/MaskedSource.java#L1557) may have to be `levelToFullResTransform[level].concatenate(fullResTransform.inverse())` and have to be applied without inversion.

I am just brainstorming and logging my thoughts. I already did (1) and it seemed to work as expected but it will need more evaluation. We should probably look at this together on a white board.

**Comment by hanslovsky** [comment]
Actually, I think I am wrong here because `fullResTransform` is the transform for level 0 and I assumed that it was for `maskLevel` in my comment.

**Comment by hanslovsky** [comment]
The remaining issue is probably a duplicate of #361 and may be related to #342

**Comment by igorpisarev** [comment]
@hanslovsky It may be helpful to try on an older version that precedes #220 to see if the bug existed before that PR. I think that's the most recent where the mask transforms were changed.

**Comment by hanslovsky** [comment]
Good point @igorpisarev, I started git-bisecting.

**Comment by hanslovsky** [comment]
The paint expansion seems to be two separate issues:
 1. The painted area is bigger than the brush indicator
 2. The painted area is the correct size initially (but does not have correct voxel size compared to the data we paint into), and then expands into the area of (1).

I am currently bisecting for (2), will post an update ASAP

**Comment by hanslovsky** [comment]
While doing the git bisect, I found that (2) is probably not a bug but rather an artifact of (1). Ever since we started updating the screen only partially, we only update the painted areas (i.e. the brush overlay size) when we paint. With (1), this means that we do update an area that is smaller (the brush overlay) than the area that was actually painted. Solving (1) should solve (2). I will investigate, why the painted area is bigger than the brush.

This is the `git bisect` that I did but it is probably irrelevant for this issue:
```
$ git bisect --log
git bisect start
# bad: [074c2279da9c80844961b3e555e7dbfea9706404] Merge pull request #267 from saalfeldlab/adaptive-mesh-resolution
git bisect bad 074c2279da9c80844961b3e555e7dbfea9706404
# bad: [a621505d307110859513cab6f62e3b05aced14c8] Merge pull request #220 from igorpisarev/fix-mask-painting
git bisect bad a621505d307110859513cab6f62e3b05aced14c8
# bad: [962544d22601db809e75ea04af826cb4358df68e] back to oraclejdk8 because it includes jfx
git bisect bad 962544d22601db809e75ea04af826cb4358df68e
# bad: [c990ca2f7bca3902d07f8ea0b758f3404baf539f] use current screen scale transform when selecting best mipmap level
git bisect bad c990ca2f7bca3902d07f8ea0b758f3404baf539f
# bad: [44add66db26824fab732c39c54c9c269b05be5c9] ... not to forget libopenjfx-jni ...
git bisect bad 44add66db26824fab732c39c54c9c269b05be5c9
# good: [9ea994e7354ee9ca4cf32d99823b866aca931de9] [maven-release-plugin] prepare release paintera-0.7.0
git bisect good 9ea994e7354ee9ca4cf32d99823b866aca931de9
# good: [c9d6e1aa1d2c1b3a085cd4d2eca3fbe1404229bc] Merge pull request #148 from saalfeldlab/auto-detect-json-adapters
git bisect good c9d6e1aa1d2c1b3a085cd4d2eca3fbe1404229bc
# good: [223b7d67a7845c4f30a3f9dba35371bb62d4fc22] Merge pull request #193 from saalfeldlab/psc-screen-scales
git bisect good 223b7d67a7845c4f30a3f9dba35371bb62d4fc22
# good: [c25e17e958a6fb7ff6c983f67f4a5bb7fc7584a1] Add mnemonic for "Revert" button
git bisect good c25e17e958a6fb7ff6c983f67f4a5bb7fc7584a1
# bad: [fd37e3a762e8767a0b920805e49b79032121168e] fix another javadoc error
git bisect bad fd37e3a762e8767a0b920805e49b79032121168e
# bad: [3ec95b1512c54e997bcb3af3c239e94d1c12665c] make 3d view work by copying rendered intervals into texture images
git bisect bad 3ec95b1512c54e997bcb3af3c239e94d1c12665c
# bad: [cc9ba261ba8bf062ffe27b3b204429023bb2d8ce] get renderer to work properly with screen scales that are powers of two
git bisect bad cc9ba261ba8bf062ffe27b3b204429023bb2d8ce
# bad: [af00ee367635f3c5b1b7f2ef580fa5c1da59f33a] split repaint requests into two separate queues (low res and higher res)
git bisect bad af00ee367635f3c5b1b7f2ef580fa5c1da59f33a
# bad: [ee9609c1daf29096d42d806adff9072792acb7d6] replace cell grid with rendering arbitrary intervals, still slow
git bisect bad ee9609c1daf29096d42d806adff9072792acb7d6
# bad: [0bd2dc08d440e89a41b9918a9a195876083950f9] experimental roi-based renderer, slow
git bisect bad 0bd2dc08d440e89a41b9918a9a195876083950f9
# first bad commit: [0bd2dc08d440e89a41b9918a9a195876083950f9] experimental roi-based renderer, slow
```

**Comment by hanslovsky** [comment]
I found that `PaintUtils.maximumVoxelDiagonalLengthPerDimension` uses L1 norm to find the projection/length of voxel diagonals onto/along the viewer axes. This is a potential bug but I do think that it is the root cause for this issue because paint expansion also happens when data and viewer axes are aligned.

**Comment by hanslovsky** [comment]
I will try `git bisect` to find the commit that caused (1)

**Comment by hanslovsky** [comment]
Actually, without the bisect, I found a potential cause for the expansion issue (at least if viewer axes and data axes are aligned):
The radii of the `DiamondShape` for painting is determined with `Math.ceil`, thus always overestimating the radius. When I switch to `Math.round` instead, it seems that no expansion is happening for isotropic data (e.g. xy in CREMI) but not enough voxels are painted along the higher-resolution dimension for anisotropic data (e.g. yz in CREMI). This may be caused by the `HyperEllipsoidNeighborhood`.

I will try to find a fix for that and also investigate the case for when data and viewer axes are not aligned.

**Comment by hanslovsky** [comment]
There are a few updates on this issue:
https://github.com/saalfeldlab/paintera/pull/385

**Comment by hanslovsky** [comment]
@dnguyen-thi this was fixed in #385 and I will probably release a new version today. I will notify you when that happens so you can try and see if this issue is fixed for you now.

**Comment by hanslovsky** [comment]
@dnguyen-thi This is available in Paintera Version `0.24.0` now. You can install the latest version through pip
```
python -m pip install paintera==0.24.0
```
or conda
```
conda install paintera=0.24.0
```
